"""
manage.py

Django's command-line utility — the entry point for all management tasks.

Flask equivalent: there is none. Flask used  flask run  or  app.run().
Django uses manage.py for everything:

    python manage.py runserver          ← start dev server (replaces flask run)
    python manage.py makemigrations     ← generate migration files from models.py
    python manage.py migrate            ← apply migrations to the DB (replaces db.create_all())
    python manage.py createsuperuser    ← create an admin account
    python manage.py shell              ← interactive Python shell with Django loaded
    python manage.py collectstatic      ← gather static files for production

This file is auto-generated by  django-admin startproject  — do not edit.
"""

import os
import sys


def main():
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "pfe_project.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Make sure it's installed and your "
            "virtual environment is activated."
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()