# Generated by Django 4.2.13 on 2026-03-25 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=12)),
                ('slot', models.CharField(max_length=20)),
                ('salle', models.CharField(blank=True, default='', max_length=50)),
                ('capacite', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'creneaux',
                'ordering': ['date', 'slot'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('domaine', models.CharField(max_length=50)),
                ('sujet', models.TextField()),
                ('annee', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'db_table': 'etudiants',
                'ordering': ['domaine', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('domaine', models.CharField(max_length=50)),
                ('specialites', models.TextField(blank=True, default='')),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('disponibilites', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'professeurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('prof', 'Professeur'), ('etudiant', 'Étudiant')], default='etudiant', max_length=20)),
                ('etudiant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.etudiant')),
                ('professeur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.professeur')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='encadrant',
            field=models.ForeignKey(db_column='encadrant_id', on_delete=django.db.models.deletion.PROTECT, related_name='etudiants_encadres', to='scheduler.professeur'),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_exam', models.FloatField(default=0.0)),
                ('score_pres', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('creneau', models.ForeignKey(db_column='creneau_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='scheduler.creneau')),
                ('etudiant', models.OneToOneField(db_column='etudiant_id', on_delete=django.db.models.deletion.CASCADE, related_name='affectation', to='scheduler.etudiant')),
                ('examinateur', models.ForeignKey(db_column='examinateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_examinateur', to='scheduler.professeur')),
                ('president', models.ForeignKey(db_column='president_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_president', to='scheduler.professeur')),
            ],
            options={
                'db_table': 'affectations',
                'ordering': ['creneau__date', 'creneau__slot'],
            },
        ),
    ]
